ALTER TABLE project_worker ADD SALARY INT;
SELECT * FROM project_worker;

UPDATE project_worker
SET SALARY =(
    SELECT SALARY 
    FROM worker
    WHERE project_worker.WORKER_ID = worker.id
);

SELECT SUM(SALARY),PROJECT_ID
FROM project_worker
GROUP BY PROJECT_ID;

CREATE TABLE costs(
    PROJECT_ID INT PRIMARY KEY,
    DAYS INT, 
    COMBINED_SALARY INT, 
    PRICE INT, 
    FOREIGN KEY(PROJECT_ID) REFERENCES project_worker(PROJECT_ID)
);

INSERT INTO costs VALUES(1, NULL, NULL, NULL);
INSERT INTO costs VALUES(2, NULL, NULL, NULL);
INSERT INTO costs VALUES(3, NULL, NULL, NULL);
INSERT INTO costs VALUES(4, NULL, NULL, NULL);
INSERT INTO costs VALUES(5, NULL, NULL, NULL);
INSERT INTO costs VALUES(6, NULL, NULL, NULL);
INSERT INTO costs VALUES(7, NULL, NULL, NULL);
INSERT INTO costs VALUES(8, NULL, NULL, NULL);
INSERT INTO costs VALUES(9, NULL, NULL, NULL);
INSERT INTO costs VALUES(10, NULL, NULL, NULL);

UPDATE costs
SET DAYS = (
    SELECT DAYS
    FROM length_of_project
    WHERE costs.PROJECT_ID = length_of_project.ID
    ),
    COMBINED_SALARY = (
    SELECT SUM(salary)
    FROM project_worker
    WHERE costs.PROJECT_ID = project_worker.PROJECT_ID
    ),
    PRICE = (
    (DAYS/30)*COMBINED_SALARY
    );

SELECT*FROM costs ORDER BY PRICE DESC;